#include "totvs.ch"

/*/{Protheus.doc} zCadastro
Monta a tela de cadastro com 3 abas
@type function
@author Diego Santana
@since 14/05/2026
@version 1.0
/*/
User Function zCadastro()
    // ===================================================================================================
    // Variáveis da Estrutura da tela: TDialog e TFolder
    // ===================================================================================================
    Local oDialog
    Local aSize := MsAdvSize() // Permite ocupar 100% da tela de acordo com o tamanho do dispositivo.
    // Abas
    Local aFolder := {"Dados Pessoais", "Endereço"}
    Local oFolder

    // ===================================================================================================
    // Variáveis da Aba 01: Cadastros
    // ===================================================================================================
    Local oSayNome
    Local oGetNome
    Local cGetNome

    // Nome Reduzido
    Local oSayNomeReduz
    Local oGetNomeReduz
    Local cGetNomeReduz

    // Data Nascimento
    Local oSayDataNasc
    Local oGetDataNasc
    Local dGetDataNasc

    // DDD
    Local oSayDDDCel
    Local oGetDDDCel
    Local cGetDDDCel

    // Celular
    Local oSayCel
    Local oGetCel
    Local cGetCel

    // Group Sexo
    Local oGroupSexo
    Local aSexo := {"Masculino", "Feminino", "Outro"}
    Local nSexo := 1 // Armazena o item do array aSexo selecionado. Inicia em 1 = Masculino
    Local oRadioSexo

    // CPF
    Local oSayCPF
    Local oGetCPF
    Local cGetCPF

    // ===================================================================================================
    // Variáveis da Aba 02: Endereço
    // ===================================================================================================
    Local oSayEndereco
    Local oGetEndereco
    Local cGetEndereco

    // Bairro
    Local oSayBairro
    Local oGetBairro
    Local cGetBairro

    // Tipo de imóvel
    Local oSayImovel
    Local aImoveis := {"Casa", "Apartamento", "Outro"}
    Local cImovel := aImoveis[1] // Armazena o valor selecionado do array aImoveis
    Local oComboImovel

    // CEP
    Local oSayCEP
    Local oGetCEP
    Local cGetCEP

    // Estado
    Local oSayUF
    Local aUF := {"AC", "AL", "AM", "AP", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RO", "RS", "RR", "SC", "SE", "SP", "TO"}
    Local cUF := aUF[1] // Armazena o valor selecionado do array aUF
    Local oComboUF

    // Cidade
    Local oSayCidade
    Local oGetCidade
    Local cGetCidade

    // =============================================================================
    // Botões para exibir os dados
    // =============================================================================
    Local oBtnFolder1
    Local aDados01
	
    Local oBtnFolder2
    Local aDados02


    // =============================================================================
    // Botões do CRUD (Incluir, alterar, Consultar e Excluir)
    // =============================================================================
    Local oBtnIncluir
    Local oBtnAlterar
    Local oBtnConsultar
    Local oBtnExcluir

    // =============================================================================
    // Estrutura da tela (TDialog com Abas)
    // =============================================================================
    oDialog := TDialog():New(aSize[7],aSize[1],720,aSize[5],'Cadastros',,,,,CLR_BLACK,CLR_WHITE,,,.T.)
    // Cria as abas
    oFolder := TFolder():New(0,0,aFolder,aFolder,oDialog,,,,.T.,,600,150)

    // ================================================================================
    // Elementos da Aba01: Cadastros
    // ================================================================================
    oSayNome := TSay():New(01,05,{||'Nome'},oFolder:aDialogs[1],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
    cGetNome := Space(30)
    oGetNome := TGet():New(10,05,{|u|IIF(Pcount()>0,cGetNome:=u,cGetNome)},oFolder:aDialogs[1],096,009,"",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGetNome,,,, )

    // Nome reduzido
    oSayNomeReduz := TSay():New(01,110,{||'Nome Reduzido'},oFolder:aDialogs[1],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
    cGetNomeReduz := Space(30)
    oGetNomeReduz := TGet():New(10,110,{|u|IIF(Pcount()>0,cGetNomeReduz:=u,cGetNomeReduz)},oFolder:aDialogs[1],60,009,"",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGetNomeReduz,,,, )

    // Data de Nascimento
    oSayDataNasc := TSay():New(01,180,{||'Data de Nascimento'},oFolder:aDialogs[1],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
    dGetDataNasc := Date() // Define a data inicial
    oGetDataNasc := TGet():New(10,180,{|u|IIF(Pcount()>0,dGetDataNasc:=u,dGetDataNasc)},oFolder:aDialogs[1],60,009,"",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,,,,,.T.)

    // DDD
    oSayDDDCel := TSay():New(01,250,{||'DDD'},oFolder:aDialogs[1],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
    cGetDDDCel := Space(4)
    oGetDDDCel := TGet():New(10,250,{|u|IIF(Pcount()>0,cGetDDDCel:=u,cGetDDDCel)},oFolder:aDialogs[1],20,009,"@E (99)",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGetDDDCel,,,, )

    // Celular
    oSayCel := TSay():New(01,280,{||'Celular'},oFolder:aDialogs[1],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
    cGetCel := Space(11)
    oGetCel := TGet():New(10,280,{|u|IIF(Pcount()>0,cGetCel:=u,cGetCel)},oFolder:aDialogs[1],40,009,"@E 9-9999-9999",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGetCel,,,,)

    // Grupo: Sexo
    oGroupSexo := tGroup():New(01,330,50,430,"Sexo",oFolder:aDialogs[1],,,.T.)
    oRadioSexo := TRadMenu():New (10,340,aSexo,,oFolder:aDialogs[1],,,,,,,,60,20,,,,.T.)
    oRadioSexo:bSetGet := {|u| IIF(PCount()==0,nSexo,nSexo:=u)} // Armazena o valor selecionado, na variável nSexo

    // CPF
    oSayCPF := TSay():New(25,05,{||'CPF'},oFolder:aDialogs[1],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
    cGetCPF := Space(14)
    oGetCPF := TGet():New(35,05,{|u|IIF(Pcount()>0,cGetCPF:=u,cGetCPF)},oFolder:aDialogs[1],96,009,"@E 999.999.999-99",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGetCPF,,,,)

    // ================================================================================
    // Elementos da Aba02: Endereço
    // ================================================================================
    oSayEndereco := TSay():New(01,05,{||'Endereço'},oFolder:aDialogs[2],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
    cGetEndereco := Space(30)
    oGetEndereco := TGet():New(10,05,{|u|IIF(Pcount()>0,cGetEndereco:=u,cGetEndereco)},oFolder:aDialogs[2],96,009,"",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGetEndereco,,,, )

    // Bairro
    oSayBairro := TSay():New(01,110,{||'Bairro'},oFolder:aDialogs[2],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
    cGetBairro := Space(30)
    oGetBairro := TGet():New(10,110,{|u|IIF(Pcount()>0,cGetBairro:=u,cGetBairro)},oFolder:aDialogs[2],60,009,"",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGetBairro,,,, )

    // Tipo de imóvel
    oSayImovel := TSay():New(01,180,{||'Tipo de Imóvel'},oFolder:aDialogs[2],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
    oComboImovel := TComboBox():New(010,180,{|u|if(PCount()>0,cImovel:=u,cImovel)},aImoveis,60,20,oFolder:aDialogs[2],,,,,,.T.,,,,,,,,,'cImovel')

    // CEP
    oSayCEP := TSay():New(01,250,{||'CEP'},oFolder:aDialogs[2],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
    cGetCEP := Space(9)
    oGetCEP := TGet():New(10,250,{|u|IIF(Pcount()>0,cGetCEP:=u,cGetCEP)},oFolder:aDialogs[2],30,009,"@E 99999-999",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGetCEP,,,,)

    // Estado
    oSayUF := TSay():New(25,05,{||'Estado'},oFolder:aDialogs[2],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
    oComboUF := TComboBox():New(35,05,{|u|if(PCount()>0,cUF:=u,cUF)},aUF,40,20,oFolder:aDialogs[2],,,,,,.T.,,,,,,,,,'cUF')

    // Cidade
    oSayCidade := TSay():New(25,50,{||'Cidade'},oFolder:aDialogs[2],,,,,,.T.,CLR_BLUE,CLR_WHITE,300,20)
    cGetCidade := Space(30)
    oGetCidade := TGet():New(35,50,{|u|IIF(Pcount()>0,cGetCidade:=u,cGetCidade)},oFolder:aDialogs[2],96,009,"",,0,,,.F.,,.T.,,.F.,,.F.,.F.,,.F.,.F.,,cGetCidade,,,, )

    // ================================================================================
    // Botões
    // ================================================================================
    oBtnFolder1 := TButton():New( 60, 20, "Exibir Dados", oFolder:aDialogs[1], {||;
    aDados01 := JsonObject():New(),;
    aDados01["nome"] := AllTrim(cGetNome),;
    aDados01["nomeReduz"] := AllTrim(cGetNomeReduz),;
    aDados01["dataNasc"] := dGetDataNasc,;
    aDados01["ddd"] := AllTrim(cGetDDDCel),;
    aDados01["celular"] := AllTrim(cGetCel),;
    aDados01["sexo"] := aSexo[nSexo],;
    aDados01["cpf"] := AllTrim(cGetCPF),;
    ExibiDados(aDados01, "ABA01");
    }, 100,15,,,.F.,.T.,.F.,,.F.,,,.F. )

    oBtnFolder2 := TButton():New( 60, 20, "Exibir Dados", oFolder:aDialogs[2], {||;
    aDados02 := JsonObject():New(),;
    aDados02["endereco"] := AllTrim(cGetEndereco),;
    aDados02["bairro"] := AllTrim(cGetBairro),;
    aDados02["tipoImovel"] := cImovel,;
    aDados02["cep"] := AllTrim(cGetCEP),;
    aDados02["uf"] := cUF,;
    aDados02["cidade"] := AllTrim(cGetCidade),;
    ExibiDados(aDados02, "ABA02");
    }, 100,15,,,.F.,.T.,.F.,,.F.,,,.F. )

    
    // ================================================================================
    // Botões de CRUD
    // ================================================================================
    oBtnIncluir := TButton():New( 170, 20, "Incluir",oDialog,{|| Alert("Incluir registro")}, 40,15,,,.F.,.T.,.F.,,.F.,,,.F. )
    oBtnAlterar := TButton():New( 170, 80, "Alterar",oDialog,{|| Alert("Alterar registro")}, 40,15,,,.F.,.T.,.F.,,.F.,,,.F. )
    oBtnConsultar := TButton():New( 170, 140, "Consultar",oDialog,{|| Alert("Consultar registro")}, 40,15,,,.F.,.T.,.F.,,.F.,,,.F. )
    oBtnExcluir := TButton():New( 170, 200, "Excluir",oDialog,{|| Alert("Excluir registro")}, 40,15,,,.F.,.T.,.F.,,.F.,,,.F. )

    // Ativa o oDialog Centralizado
    oDialog:Activate(,,,.T.)
Return

/*/{Protheus.doc} ExibiDados
Função reutilizável para exibir os dados.
@type function
@author Diego
@since 14/05/2026
@param aDados, JsonObject, JsonObject Contendo os dados a ser exibidos.
@param cAba, character, Descrição da aba, podendo ser "ABA01" ou "ABA02"
/*/
Static Function ExibiDados(aDados, cAba)
    Local cMsg := ""

    If cAba == "ABA01"
        cMsg += "Nome...........: " + aDados["nome"] + CRLF
        cMsg += "Nome Reduzido..: " + aDados["nomeReduz"] + CRLF
        cMsg += "Data Nasc......: " + DtoC(aDados["dataNasc"]) + CRLF
        cMsg += "DDD/Celular....: " + aDados["ddd"] +" "+ aDados["celular"] + CRLF
        cMsg += "Sexo...........: " + aDados["sexo"] + CRLF
        cMsg += "CPF............: " + aDados["cpf"]
        MsgInfo(cMsg, "Dados Pessoais")
    ElseIf cAba == "ABA02"
        cMsg += "Logradouro.....: " + aDados["endereco"] + CRLF
        cMsg += "Bairro.........: " + aDados["bairro"] + CRLF
        cMsg += "Tipo de Imóvel.: " + aDados["tipoImovel"] + CRLF
        cMsg += "CEP............: " + aDados["cep"] + CRLF
        cMsg += "Estado.........: " + aDados["uf"] + CRLF
        cMsg += "Cidade.........: " + aDados["cidade"]
        MsgInfo(cMsg, "Endereço")
    Else
        // Se não especificar a aba, mostra tudo de uma vez
        MsgInfo("Falha na exibição dos dados", "Nenhum Registro encontrado")
    EndIf
Return
